version: '3.8'

services:
  app_franquicias:
    build:
      context: .
    container_name: franquicias-api
    ports:
      - "8080:8080"

    env_file:
      - ${ENV_FILE}
    restart: always
    depends_on:
      db_franquicias:
        condition: service_healthy

  db_franquicias:
    image: mysql:8.0.33
    container_name: db_franquicias
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: franchises_db
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 3
